---
# tasks file for join-workers
- name: Copy token to wokers
  copy: src={{ token_file }} dest=join_token

- name: Joining worker nodes to cluster
  shell: |
    kubeadm reset -f
    cat join_token | tail -2 > out.sh
    sh out.sh