---
# tasks file for prereqs
# initial tasks to do before actually setting up kubernetes
- name: update all packages
  yum:
    name: '*'
    state: latest
  register: task_result

- name: disable selinux on all nodes
  selinux:
    state: disabled
  register: task_result

- name: reboot nodes if any changes are made
  reboot:
  when: task_result is changed

- name: add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: update iptables
  shell: |
    echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
    echo '1' > /proc/sys/net/bridge/bridge-nf-call-ip6tables    

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

