---
# tasks file for prereqs
- name: disable selinux on all nodes
  selinux:
    state: disabled
  register: task_result

- name: reboot nodes if any changes are made
  reboot:
  when: task_result is changed

- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10252/tcp
    - 10255/tcp
    
